### Создаем сотрудника №1
POST http://localhost:8080/employyee/add
Content-Type: application/json

{
  "firstName": "Красотин",
  "lastName": "Андрей"
}

### Создаем сотрудника №2
POST http://localhost:8080/employyee/add
Content-Type: application/json

{
  "firstName": "Мухитов",
  "lastName": "Жандос"
}

### Получаем всех сотрудников
GET http://localhost:8080/employyee/getAll

### Ищем сотрудника
GET http://localhost:8080/employyee/find?firstName = Мухитов&lastName = Жандос

### Удаляем сотрудника
GET http://localhost:8080/employyee/remove?firstName = Мухитов&lastName = Жандос